name: Generate
on:
  workflow_dispatch:
  schedule:
    - cron: '27 14 * * *'
concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  update:
    permissions:
      contents: write # to fetch and commit code
      pull-requests: write # to create pull requests
      actions: write # to manually dispatch checks on the pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: '.python-version'
      - run: pipx install poetry~=2.0
      - run: poetry install
      - run: poetry run scripts/download_sa_advisories.py
      - run: poetry run scripts/precache_nodes.py
      - run: rm -rf advisories/
      - run: poetry run scripts/generate_osv_advisories.py
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GENERATOR_GH_TOKEN }}
          title: 'feat: update advisories'
          body: >
            ðŸ¤– beep boop - looks like there's some changes to the advisories!
          branch: 'bot/update-advisories'
          author: |
            github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: 'feat: update advisories'
